# 数据挖掘：交互动态内容

*  本周主要内容： XHR 请求实践示例
*  20春_Web数据挖掘_week10
*  电子讲义设计者：廖汉腾, 许智超

## 上周内容：Selenium交互实践

以微信公众平台网站为例，使用Selenium控制浏览器进行交互，登入及取数据的过程都需要更复杂的表单交互，目标是根据需求的关键词，以正确的流程使用Selenium操控浏览器去模拟用户输入，以返回相关内容。

## 本周内容： XHR 请求实践

以国家数据库为例，在遇到爬虫抽取结果失败时，要能学会逆向工程/反向工程，找到交互动态内容的机制。

交互动态内容的机制，发现是XHR请求的话，学习使用requests模块，也是requests_html的大哥，将交互动态内容下下来。


### 本电子讲义说明

本电子讲义为一系列课程的主要教材
* 课程：
  * 20春_Web数据挖掘 （中山大学南方学院）
* 电子讲义设计者：廖汉腾, 许智超

# 国家数据库

国家数据库[分省年度(fsnd)数据入口页面](http://data.stats.gov.cn/adv.htm?cn=E0103)左侧点开可以看到不同的地区分类，如"八大经济区域"，要如何按结构抓取呢？

请大家运用Xpath知识，在Chrome实践成功之后，使用requests_html抓取试试？

In [1]:
# 国家数据库 requests_html
import pandas as pd
from requests_html import HTMLSession

In [2]:
url = "http://data.stats.gov.cn/adv.htm?cn=E0103"
session = HTMLSession()
r = session.get( url )

In [3]:
# Chrome 实践成功 xpath:  $x('xpath应该是什麽？')
r.html.lxml.xpath('xpath应该是什麽？')

XPathEvalError: Invalid expression

# 各阶段目标

In [23]:
# 初阶目标成果应如：{'八大经济区域': ['东北地区', '北部沿海', '东部沿海', '南部沿海', '黄河中游', '长江中游', '西南地区', '大西北地区']}
# 中阶目标成果应如下：

{'全部地区': []}
{'常规分类': ['华北', '东北', '华东', '中南', '西南', '西北']}
{'热点地区': ['长江三角洲', '环渤海地区', '泛珠三角', '东部地区', '西部地区']}
{'八大经济区域': ['东北地区', '北部沿海', '东部沿海', '南部沿海', '黄河中游', '长江中游', '西南地区', '大西北地区']}
{'三大地带': ['东部地带', '中部地带', '西部地带']}

In [20]:
df

   dbcode exp      id  isParent      name   open     pid   wd
0    fsnd      110000      True       北京市  False  100001  reg
1    fsnd      120000      True       天津市  False  100001  reg
2    fsnd      130000      True       河北省  False  100001  reg
3    fsnd      140000      True       山西省  False  100001  reg
4    fsnd      150000      True    内蒙古自治区  False  100001  reg
..    ...  ..     ...       ...       ...    ...     ...  ...
7    fsnd      610000      True       陕西省  False  900003  reg
8    fsnd      620000      True       甘肃省  False  900003  reg
9    fsnd      630000      True       青海省  False  900003  reg
10   fsnd      640000      True   宁夏回族自治区  False  900003  reg
11   fsnd      650000      True  新疆维吾尔自治区  False  900003  reg

[133 rows x 8 columns]

In [133]:
# 阶段性目标：地区
df_flat.query('name=="广东省"')

     index  i      id  isParent name  level     pid pname    ppid  ppname
45      18  3  440000     False  广东省      2  100004    中南  100000    常规分类
69      42  3  440000     False  广东省      2  200003  泛珠三角  200000    热点地区
84      57  9  440000     False  广东省      2  200004  东部地区  200000    热点地区
109     82  1  440000     False  广东省      2  800004  南部沿海  800000  八大经济区域
138    111  9  440000     False  广东省      2  900001  东部地带  900000    三大地带

In [ ]:
# 阶段性目标：指标

In [ ]:
# 阶段性目标：分省年度数据

In [ ]:
# 终极目标：分省年度数据＋指标＋地区集成